# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_auto_20170630_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='reservation_type',
        ),
        migrations.AddField(
            model_name='instrument',
            name='reservation_type',
            field=models.ManyToManyField(to='instrument.ReservationType'),
        ),
    ]
